### ISSUE TITLE
Fix hanging on execute_command

### ISSUE THREAD

**Issue by Etang21** [gslab-econ/gslab_make#35]
Follows [issue 261 in PhoneAddiction](https://github.com/gentzkow/PhoneAddiction/issues/261).

When running many bootstrap iterations in R for the PhoneAddiction repo, we found that the R files ran correctly when run using `RScript`, but hung and did not complete when run using `gslab.run_r`. The diagnosis for this appears to be the [`process.wait()` statement](https://github.com/gslab-econ/gslab_make/blob/771ea211f0bed9d6556f7ec6dae8527dd5eecdba/gslab_make/private/programdirective.py#L115), which may block if pipes overflow. From the documentation,

> Note This will deadlock when using stdout=PIPE or stderr=PIPE and the child process generates enough output to a pipe such that it blocks waiting for the OS pipe buffer to accept more data. Use Popen.communicate() when using pipes to avoid that.

This StackOverflow discussion offers another explanation of [the difference between wait and communicate](https://stackoverflow.com/questions/12965023/python-subprocess-popen-communicate-equivalent-to-popen-stdout-read).

The best fix appears to be simply removing the `process.wait()` line, as the subsequent `process.communicate()` line [already calls wait internally](https://stackoverflow.com/questions/44456996/does-popen-communicate-implicitly-call-popen-wait). The one concern is that `communicate()` cannot handle output which is too large to be buffered in memory. ("Too large" is on the order of [gigabytes](https://stackoverflow.com/questions/6880090/alternatives-to-python-popen-communicate-memory-limitations) or [many megabytes](https://stackoverflow.com/questions/1180606/using-subprocess-popen-for-process-with-large-output) here). Since our outputs are mostly R logs, though, it seems that `communicate()` should be sufficient for our purposes.

Task list
- [x] Remove `process.wait()` from `Directive.execute_command()`

@Houdanait tagging you here if you have any other thoughts on wait vs communicate!

**Comment by Houdanait** [comment]
Hi @Etang21 
We've had successive issues with this command (See #166 #33) so I think it is high time we implement a change here. 

I will read around, but I think what you say is accurate, i doubt we would ever run into an issue where the output that must be returned will be too large.

**Comment by Etang21** [comment]
Ah excellent! I was wondering about Zane's change to [remove the timeout](https://github.com/gslab-econ/gslab_make/pull/34/commits/0f978e18b5d61a99ed20b290c84d2fc092dfe56d), and that clears up the rationale behind it. Which issue is 166, by the way? I'm not seeing an issue 166 in this repo.

**Comment by Houdanait** [comment]
@Etang21 Oh yes, I can explain that over a call (Easier), because we were trying a few things to fix this.

**Comment by Etang21** [comment]
@Houdanait sounds good for a call! I'll shoot you an email to schedule.

**Comment by Etang21** [comment]
@Houdanait glad we got to call yesterday! I'm following up on one of the threads we talked about.

I have the change locally on my machine (removing the `process.wait()` statement from `run_r`), but don't have admin permissions to push to the repo (similar to [your comment here](https://github.com/gslab-econ/gslab_make/issues/33#issuecomment-782407826)). Could you add me as an admin to the repo so I can push the changes, or is there a better way to get those changes merged in? I'm also happy to tag Matt if he is the only one who can add me.

**Comment by Houdanait** [comment]
Hi @Etang21 just to clarify. 

1. I thought we said we would **modify** `process.wait()` for `process.communicate()`
2. To be precise, the change will be made in `program_directive.py` not in `run_r `right?

For the change, I will implement it, let's just agree clearly on what we are doing, and i'll make it no worries :)

**Comment by Etang21** [comment]
@Houdanait thanks for asking these two :)

(2) You're totally right, yes! I wrote the wrong function name. The line I'm proposing we remove is [this one](https://github.com/gslab-econ/gslab_make/blob/771ea211f0bed9d6556f7ec6dae8527dd5eecdba/gslab_make/private/programdirective.py#L115) in `program_directive.py`.

(1) Here I actually do think we should remove `process.wait()` completely, since there is already a `process.communicate()` on the next line of the function. This existing call to `communicate()` should do the waiting that we want. What do you think?

**Comment by Houdanait** [comment]
Perfect @Etang21 !! I'll go ahead and implement the change :)

**Comment by Etang21** [comment]
@Houdanait awesome, sounds good!

**Comment by gentzkow** [comment]
@Etang21 Just made you an administrator of the `gslab_make` repo.

**Comment by Etang21** [comment]
@gentzkow thanks so much! While we're at it, is there any chance you could make me an admin of the `template` repo too?
