### ISSUE TITLE
Default config file for update_paths

### ISSUE THREAD

**Issue by szahedian** [gslab-econ/gslab_make#41]
Follows [comment](https://github.com/gentzkow/template/issues/40#issuecomment-897133642) of [issue](https://github.com/gentzkow/template/issues/40).

The purpose of this issue is to change how config files are loaded. We want to update paths using two config files: the default one and a second one which users can use to override default settings.

Task list
- [x] Change to [make_utility.py](gslab_make/make_utility.py) in accordance with guidance given [here](https://github.com/gentzkow/template/issues/40#issuecomment-897207031).

**Comment by szahedian** [comment]
@gentzkow here's an update on this issue. I made changes following changes based on [this comment of yours](https://github.com/gentzkow/template/issues/40). 

Currently, `config_user.yaml` stores 
* Paths to external dependencies
* Local executable names

The changes I've pushed assume the following
* `config.yaml` stores default local executable names, which are can overridden by optional `config_user.yaml` file.
* Optional `config_user.yaml` file stores paths to external dependencies. If no external dependencies, no `config_user.yaml` is needed.

In both cases, if `config_user.yaml` doesn't exist or the relevant section of the yaml file (`local: executables:` or `external:`) don't exist, the script continues.

I have a few questions about these changes:
1. Given that other projects depend on `gslab_make`, are these changes safe to make?
2. Do these changes require attendant changes to other code in the repo e.g. unit tests?
2. I assume these changes will require changes to [this page of the documentation](https://gslab-econ.github.io/gslab_make/pages/utility.html).

**Comment by gentzkow** [comment]
Thanks! This sounds great.

(1) Not sure. Will this cause an existing `make.py` script to break? I would have thought these lines

> PATHS = gs.update_paths(PATHS)
> gs.update_executables(PATHS)

would be fine. Does it break if default local executable names are not present in `config.yaml`? Maybe we could change that so that it runs (and maybe just gives a warning) if those are missing in `config.yaml` but present in `config_user.yaml` so things remain backwards compatible.

(2) Not sure whether this affects any unit tests. Maybe you can try running them and see if something breaks. 

(3) Yes! Let's change that.

**Comment by szahedian** [comment]
1. I've updated the code so that it can support the old config file setup. It does come at the cost of clunkier style. 
2. The latest commit passes the unit tests, all 158 of them!

Remaining todo: 
1. Build documentation. Sphinx build is currently failing on my machine, so I'm working through that.
2. Add warning message in the event that default executable options not present in `config.yaml`.

**Comment by gentzkow** [comment]
OK. Thanks!

If it's much clunkier I'm open to the option of not maintaining backward compatibility. Since the repos clone `gslab_make` at fixed revisions they shouldn't break until that is updated.

**Comment by szahedian** [comment]
The new code is about twice as long, but I don't think it's too hard to understand. And it's not as lengthy as some functions in gslab_make. Compare the [new code](https://github.com/gslab-econ/gslab_make/blob/17d9deca056a9d9be3035d41c767c486980100c1/gslab_make/make_utility.py) (line 42) to the [old code](https://github.com/gslab-econ/gslab_make/blob/27989bff1aee3a5809faa5f65ca717b86994e0b2/gslab_make/make_utility.py) (line 38).

**Comment by gentzkow** [comment]
ok! that looks fine

>

**Comment by szahedian** [comment]
@gentzkow I haven't made any changes to the source code since you last looked at it. The testing suite now tests the updated functionality. I opened #42 to merge these changes. 

If you have no further comments, I'll go ahead and merge!

**Comment by gentzkow** [comment]
Great! Green light to merge

**Comment by szahedian** [comment]
During my final check, I took another look at the testing suite and I noticed a problem with several of the unit tests, [these for example](https://github.com/gslab-econ/gslab_make/blob/27989bff1aee3a5809faa5f65ca717b86994e0b2/test/test_make_utility.py#L37-L69). They go like this.

```
def test_something(self):     
     try:
          some_code_that_possibly_throws_error
     except Exception as e:
          self.assertRaises(Exception, e)
```

Tests written this way will always pass. Either code in the try-block runs without issue and the test passes, or the try-block code triggers an exception, which is caught and tautologically asserted. There are test like this across most of the test files.

I've held off on merging my changes for this issue because I'd like to run them through proper unit tests before merging. 

I think correcting these tests would be best done in its own issue?

**Comment by gentzkow** [comment]
Oops! Wow. Thanks for catching.

Just to test my understanding, this issue is using `assertRaises()`, right? That asserts that `Exception` is raised which of course it is once we're in the `except` block. You would have expected the code inside the `except` block to report that the test has failed with `Exception`. 

Yes, let's fix this in a separate issue.

**Comment by szahedian** [comment]
Yes, to explain another way, these tests are meant to ensure that an error is raised under conditions that break the code. But whether or note the code raises an error, the intended behavior, the tests pass.

**Comment by szahedian** [comment]
Opened #43 to address this issue.

**Comment by szahedian** [comment]
A quick update on progress here:
1. I pulled in changes to test syntax made in #43.
2. I made some additional edits to the tests to accommodate the new default config system.

The tests pass, but do run a bit noisier:
```
(template) zahedian@SEIPR-C02G3175ML86 gslab_make % python -m unittest discover
........................WARNING! config.yaml does not include default executable names.
.WARNING! config.yaml does not include default executable names.
.WARNING! config.yaml does not include default executable names.
.......................................................................................................................
----------------------------------------------------------------------
Ran 145 tests in 2.867s

OK
```
I've checked and these warnings are correctly issued. If they are no problem, I'll go ahead and merge!

**Comment by jc-cisneros** [comment]
@gentzkow I think we can safely merge these changes given they include backwards compatibility (per https://github.com/gslab-econ/gslab_make/issues/41#issuecomment-902393067). As a reminder, the changes are summarized [here](https://github.com/gslab-econ/gslab_make/issues/41#issuecomment-899751202) (they essentially allow the user to override default local executable names with what they define in `config_user.yaml`). If needed we can discuss possible new features/fixes as the new predocs familiarize themselves with `template`.

cc. @snairdesai

**Comment by gentzkow** [comment]
OK! Cleared to merge.

**Comment by jc-cisneros** [comment]
### Summary

Final resolution in [PR for #41](https://github.com/gslab-econ/gslab_make/pull/42#issuecomment-1648695628):

> Replace the current config.yaml/config_user.yaml logic to reduce extra steps for users that will adhere to defaults. Per https://github.com/gslab-econ/gslab_make/pull/42#issuecomment-1638696617, that would imply finding a solution that can implement default values both for external directories (i.e., the default external directory is the Dropbox directory within the user's system) and executable names.
> 
> Per https://github.com/gslab-econ/gslab_make/pull/42#issuecomment-1648095892 and our conversation, we will prioritize making template (and its Workflow) fully compatible with Overleaf and can then go over the [other To-do tasks](https://github.com/gentzkow/template/wiki/Project-Outline) that would improve the user's experience if there is bandwidth.
