### ISSUE TITLE
Eliminate `future` dependency from package

### ISSUE THREAD

**Issue by szahedian** [gslab-econ/gslab_make#49]
This issue stems from https://github.com/gentzkow/template/issues/53#issuecomment-1094304541. 

We want to streamline lab tools to use fewer dependencies for the sake of performance. We noticed that the `future` module is used sparingly throughout this repo, and would like to eliminate it.

**Comment by szahedian** [comment]
Hello, @gentzkow! Here is an update on this. 

After some digging, I've found that the `future` is used in two ways in `gslab_make()`. 
1. We use the `future` module's `raise_from()` function to raise exceptions. I believe these can be eliminated by replacing each `raise_from()` with a `raise` statement.
2. We use the `future` module to distinguish between ASCII and Unicode strings. In Python 3, all strings are stored in the more complete Unicode format. But before Python 3, base strings are stored in the more primitive ASCII format, with Unicode supported as an add-on. 

    Some functions in this package check whether a variable is a Unicode string e.g. see [here](https://github.com/gslab-econ/gslab_make/blob/c98984058dcc17e4958f8d63156c6a88cb35a996/gslab_make/private/utility.py#L21-L36). This can't be done without importing an external package. So our goal of eliminating a package is incompatible with keeping this functionality.

**Comment by gentzkow** [comment]
Thanks @szahedian. Is there any reason we'd need the functionality in (2) if we're running everything in Python 3? If not, can't we just get rid of it?

**Comment by szahedian** [comment]
@gentzkow I think that's right. Let me move forward with that and make sure everything works!
