### ISSUE TITLE
Allow run if python git not available

### ISSUE THREAD

**Issue by szahedian** [gslab-econ/gslab_make#51]
Follows gentzkow/template#54. We would like to remove the `git` python dependency from gentzkow/template. This involves editing gslab_make so as to allow logging even if the not being run inside a git repo. The python git dependency is used in [check_setup.py](https://github.com/gslab-econ/gslab_make/blob/4b63825e5c3bac883dfd7d7be4741c9d931c26a0/gslab_make/check_repo.py).

**Comment by szahedian** [comment]
@gentzkow, we created this issue to remove the `gitpython` dependency from `gslab_make`, so that we could delete it from the list of dependencies necessary to run `gentzkow/template`. This was because the template environment was taking a while to solve. If I understand correctly, thanks to Sameer and Juan Carlos' work in gentzkow/template#59, solving the environment's template is no longer time-intensive. Thus I think we can abandon this issue. Let me know if this sounds okay to you.

**Comment by gentzkow** [comment]
Sounds great

**Comment by szahedian** [comment]
## Summary

In this issue, we set out to remove the `gitpython` dependency from `gslab_make`, in order to delete it from `gentzkow/template`. Progress in gentzkow/template#59 has obviated the need for this, so we close this issue without merging any changes.
