### ISSUE TITLE
Resolve jquery vulnerability flagged by GitHub

### ISSUE THREAD

**Issue by snairdesai** [gslab-econ/gslab_make#61]
The purpose of this issue follows closely from #59. We received an updated `dependabot` flag relating to `jquery`:

<img width="547" alt="Screen Shot 2023-07-10 at 7 04 13 PM" src="https://github.com/gslab-econ/gslab_make/assets/63830369/b3848468-4ec7-4d7e-9f08-d62323dbfa41">

We were conservative in the outdated documentation we removed in the prior issue, so I think we should investigate further which underlying files are no longer needed to build the website.

cc @jc-cisneros

**Comment by snairdesai** [comment]
_Update:_ What's strange about the above flag is that the file referenced by `dependabot` was removed in the last issue (#59) and no longer exists. The tag is [here](https://github.com/gslab-econ/gslab_make/security/dependabot/2), and the hyperlink to the file referenced is [broken](https://github.com/gslab-econ/gslab_make/blob/master/docs/_static/jquery-3.2.1.js) as the file has been removed.

This is likely something under the hood of one of the other `_.js` files. Will look into this further.

**Comment by snairdesai** [comment]
_Update_: @jc-cisneros and I discussed this offline, and from both of our investigations, there does not seem to be any indication that the `jquery-3.2.1.js` file lives anywhere in `gslab_make`, as we explicitly removed it in #59. We will continue to investigate, and may need to look deeper into the Dependabot action which is generating the flag to begin with.

**Comment by snairdesai** [comment]
_Update:_ @jc-cisneros and I looked into this once more and could not find any reference to `jquery-3.2.1.js`. We will close this out for now, but if this alert is generated again, we may reach out to `GitHub` support to determine what exactly the `Dependabot` is scanning for.

**Comment by jc-cisneros** [comment]
@snairdesai I agree. The outdated version of `jquery` that has vulnerabilities is not in the repository and is not used in the source code of the [documentation webpage](https://gslab-econ.github.io/gslab_make/). Therefore, I don't think we have that vulnerability flagged by `Dependabot`. If that is the case, I agree that we should understand what is being scanned by `Dependabot`. If it is scanning previous commits, we will keep getting this warning.

**Comment by snairdesai** [comment]
Thanks @jc-cisneros! I will close this out and we can open a new issue in the future to investigate the `Dependabot` scanning if we see additional flags in the future.

**Comment by snairdesai** [comment]
### Summary
---

In this issue (#61) we investigated a recurring `Dependabot` flag to a potential vulnerability in `jquery-3.2.1.js`, a script which previously lived in the `gslab_make` repository and built an older version of the website. We removed this script and any related references in a previous issue (#59), and ensured the website was still built successfully.

There are no longer any references to the outdated file, so we are closing out this issue for now. We may continue to investigate this if additional alerts are flagged in the future.

**Comment by snairdesai** [comment]
### Summary
---

In this issue (#61) we investigated a recurring `Dependabot` flag to a potential vulnerability in `jquery-3.2.1.js`, a script which previously lived in the `gslab_make` repository and built an older version of the website. We removed this script and any related references in a previous issue (#59), and ensured the website was still built successfully.

There are no longer any references to the outdated file, so we are closing out this issue for now. We may continue to investigate this if additional alerts are flagged in the future.

**Comment by snairdesai** [comment]
We received another `Dependabot` flag this morning, so I'm reopening this issue with a new purpose: investigating where `Dependabot` queries to generate flags, and attempting to resolve directly. We may need to reach out to `GH` support.

cc @jc-cisneros

**Comment by snairdesai** [comment]
@jc-cisneros I've been reading through [this documentation](https://docs.github.com/en/code-security/dependabot/dependabot-alerts/about-dependabot-alerts) so far, still need to do more digging but flagging here for now.

**Comment by snairdesai** [comment]
### Summary
---

After further research on [Dependabot code security flags](https://docs.github.com/en/code-security/dependabot/dependabot-alerts/about-dependabot-alerts), I realized that this is a bug on `GitHub` dependabot's end (see [here](https://github.com/dependabot/dependabot-core/issues/4129#issuecomment-1211014715)), and we did indeed properly remove the `jquery` file which had generated the prior flag. The dependabot was simply not synced with the current state of the repo.

I reached out to GitHub support to resolve this, and they have now done so. As a result, we [no longer have any security flags](https://github.com/gslab-econ/gslab_make/security/dependabot).
